### ISSUE TITLE
Ready to add to Surplus README?

### ISSUE THREAD

**Issue by adamhaile** [tinchoz49/parcel-plugin-surplus#2]
I wanted to thank you for taking the time to make a Parcel plugin for surplus.  Is this at a state where you think it's ready to be linked from the Surplus README page?

**Comment by tinchoz49** [comment]
Hi @adamhaile ! how are you? It's nothing, it was something that I really want to do to give a `easy start` developing with Surplus :+1: !

And yes, it's ready to be linked. I can do a PR if you want.
