### ISSUE TITLE
Use with HMR?

### ISSUE THREAD

**Issue by gilbert** [tinchoz49/parcel-plugin-surplus#3]
Hi, do you have any tips on using surplus with parcel's HMR? At the moment I have their "hello world" example working, but every time I save it attaches a new element to the dom.

**Comment by tinchoz49** [comment]
Hi gilbert! that is because how it works the parcel runner. It doesn't have a `mount` function like the common vdom libraries.

What you can do to solve this is:

```javascript
const root = document.getElementById('js-root')
root.innerHTML = ''
root.appendChild(view)
```

Take a look my example: https://github.com/tinchoz49/parcel-plugin-surplus/blob/master/example/src/index.js#L11

**Comment by gilbert** [comment]
I see, thank you, this works. For learning, is there a way to do this by making surplus detect when its dom element / stream is removed from the page?

**Comment by tinchoz49** [comment]
I think this could be an enhancement for surplus, maybe adding a function `mount` to the surplus runner that will do the same as the code above.

**Comment by gilbert** [comment]
Makes sense, thank you!
