### ISSUE TITLE
Compilation error when compiling .tsx with generics.

### ISSUE THREAD

**Issue by Sh4rK** [tinchoz49/parcel-plugin-surplus#5]
Hi, I think I found a bug, but it might be just misconfiguration.

I'm trying to use parcel with this plugin to bundle a Surplus.js app written in Typescript.
The problem can be reproduced with this tsx file:
```tsx
import * as Surplus from "surplus";
let a: Array<number> = [1, 2, 3];
```
The error I get when trying to run parcel on this project:
```
project_path>yarn parcel build src/index.html
yarn run v1.7.0
$ project_path/node_modules/.bin/parcel build src/index.html
×  project_path/src/main.tsx: element missing close tag at line 1 col 12: ``<number> = [1, 2, 3];''
    at ERR (project_path/node_modules/surplus/compiler/index.js:374:15)
    at jsxElement (project_path/node_modules/surplus/compiler/index.js:165:17)
    at program (project_path/node_modules/surplus/compiler/index.js:92:31)
    at parse (project_path/node_modules/surplus/compiler/index.js:84:12)
    at Object.compile (project_path/node_modules/surplus/compiler/index.js:1540:45)
    at TSAsset.pretransform (project_path/node_modules/parcel-plugin-surplus/lib/surplus-asset.js:20:39)
    at TSAsset.process (project_path/node_modules/parcel-bundler/src/Asset.js:202:18)
    at <anonymous>
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

This seems like the tsx source is ran through the surplus compiler before being compiled by the ts compiler, and the surplus compiler thinking this is a JSX starting tag.

Do you think this is a bug, and if it is, can it be fixed?

**Comment by tinchoz49** [comment]
Hi @Sh4rK! it's true, i'm going to do some tests about running surplus after ts using `"jsx": "preserve"` thanks for reporting this

**Comment by Sh4rK** [comment]
Cool, thanks!

**Comment by tinchoz49** [comment]
Hi @Sh4rK, can you try the new version?

**Comment by tinchoz49** [comment]
Sorry, I forgot, you need to add a configuration in your tsconfig.json 

https://github.com/tinchoz49/parcel-plugin-surplus#for-typescript-users

**Comment by Sh4rK** [comment]
It seems to work great, thanks for the really quick fix! :)

**Comment by Sh4rK** [comment]
(It's funny that fixing this was actually _removing_ the TS specific parts :) )

**Comment by tinchoz49** [comment]
haha yes, it's true. The issue is that parcel first runs TS and then runs the result with the JS asset. I didn't know that, so basically I was compiling surplus twice. 

The other issue was that surplus only compiles JS so it's necessary to compile the TypeScript code first and then runs the Surplus compiler.

Thanks for reporting it!
