### ISSUE TITLE
Please consider reducing the list of extensions to simply .jsx

### ISSUE THREAD

**Issue by Qix-** [tinchoz49/parcel-plugin-surplus#7]
Compiling all .js files means you must also be able to parse all language extensions, which is very much not the case. For example, using `parcel-plugin-surplus` prevents me from using `mermaid` _anywhere_ in the project because regex parsing seems bugged.

Since Parcel doesn't really do "configuration" very well, it's hard for me to tell this plugin to ignore non-`.jsx` files.

**Comment by tinchoz49** [comment]
Hi @Qix- ! I don't use `jsx` extension in my projects (bad habits of using create-react-app for too long) . What do you think about adding support for a `surplus` configuration in the package.json?

```
{
...
  "surplus": {
    "include": [
      "src/**/*.jsx"
    ],
    "exclude": [
      "node_modules"
    ]
  }
}
```

**Comment by Qix-** [comment]
Hrmm perhaps. I think it's a bit antithetical to Surplus and Parcel, however - parcel abhors configuration, for instance.

However, I don't really see a way around it. However (and perhaps this is an improvement to be made in Surplus proper) it *would* be a good indicator that a source file is meant to be compiled if it has `import * as Surplus from 'surplus'` somewhere within it. Ignoring any JS files that don't have that would be a good start.

**Comment by tinchoz49** [comment]
> ...if it has import * as Surplus from 'surplus' somewhere within it. Ignoring any JS files that don't have that would be a good start.

Yes, we can do that. I think I have something like that in a old version.

**Comment by Qix-** [comment]
That'd be really great :)

**Comment by tinchoz49** [comment]
New release v1.3.0

**Comment by Qix-** [comment]
Give me a few minutes and I'll give it a test :) thanks for such a quick fix.

**Comment by Qix-** [comment]
Yep, that did it :) Thanks so much!
